### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by nachimedali** [Nomikxyz/diabetic-retinopathy-screening#1]
Hi,

Great work!! tried to follow up your scripts but till now, did not found how to run your code, and from where to start. Can you, please, just write steps to follow to make things work?

Thanks,

**Comment by javathunderman** [comment]
@nachimedali Yeah, no problem. Will update this issue page when it's done.

**Comment by javathunderman** [comment]
@nachimedali latest commit should have a good tutorial. Let me know what you think.

**Comment by javathunderman** [comment]
Also publishing a post to Medium on this.

**Comment by javathunderman** [comment]
Medium link here: https://medium.com/@javathunderman/how-to-get-started-with-the-diabetic-retinopathy-project-f1c2700188ae

**Comment by fdatoo** [comment]
@javathunderman You should use GitHub Wikis for this.
